[platformio]
core_dir = .pio-core
default_envs = m5sticks3

[env:m5sticks3]
platform = https://github.com/pioarduino/platform-espressif32.git#54.03.21
board = esp32-s3-devkitc1-n8r8
framework = arduino
extra_scripts =
  pre:scripts/pio_env.py
  pre:scripts/patch_audio_i2s.py

monitor_speed = 115200
upload_speed = 1500000
upload_protocol = esptool
upload_flags =
  --before=usb-reset
  --after=hard-reset

board_build.flash_mode = qio
board_build.psram = enabled
board_upload.flash_size = 8MB
board_upload.maximum_size = 8388608
board_build.partitions = max_app_8MB.csv

build_flags =
  -DARDUINO_USB_MODE=1
  -DARDUINO_USB_CDC_ON_BOOT=1
  -DBOARD_HAS_PSRAM
  -DCORE_DEBUG_LEVEL=3
  -Ddsps_biquad_sf32=dsps_biquad_f32

lib_deps =
  m5stack/M5Unified
  https://github.com/schreibfaul1/ESP32-audioI2S.git

[env:m5sticks3-manual]
extends = env:m5sticks3
upload_flags =
  --before=no-reset
  --after=hard-reset
